### ISSUE TITLE
Some suggestions for the Shop - categories and role related items

### ISSUE THREAD

**Issue by Necropollis** [CatalysmsServerManager/7-days-to-die-server-manager#207] opened 2020-07-19 12:39 UTC
1. It would be nice, if we can makie categories like weapons/modifications/Tools

2. If you create a new shop item, it would be very awesome, if we can select between all roles/a given role/this role and below/this role and above.
Idea is, we have some premium items included, that should just be viewable for premium players or above.

Thanks in advance
Orakel

**Comment by niekcandaele** [comment] 2020-07-19 12:42
1. Duplicate of https://github.com/CatalysmsServerManager/7-days-to-die-server-manager/issues/59

2. Sounds good!


In the future, please only one request per issue (Is much easier for us to keep track of things) and follow the template. The template is there for a reason :slightly_smiling_face: 

I will close this issue, you can remake it with the proper format

**Closed by niekcandaele** 2020-07-19 12:42 UTC
Labels: enhancement
