### ISSUE TITLE
Shop - Categories

### ISSUE THREAD

**Issue by MADMAN72** [CatalysmsServerManager/7-days-to-die-server-manager#221] opened 2020-07-22 19:30 UTC
It is difficult to quickly find an item you are looking for if you have a large shop.

Could we create a way to organize the shop better by allowing it to be broken down into categories?  Examples: Food, Drinks, Decor, Vehicles, etc.

Thanks!

**Comment by niekcandaele** [comment] 2020-07-22 19:30
Good suggestion, duplicate of https://github.com/CatalysmsServerManager/7-days-to-die-server-manager/issues/59 though :smile:

**Closed by niekcandaele** 2020-07-22 19:30 UTC
Labels: enhancement
